/* *****************************************************************************
 * This file has been generated by boschicon.js script.
 * DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
 *
 * source: Bosch-UI-Icon-2-1.zip
 * date: Thu, 15 Dec 2022 10:55:41 GMT
 **************************************************************************** */

const iconNames: string[] = [
  'alert-error',
  'alert-info',
  'alert-success',
  'alert-warning',
  'checkmark',
  'close',
  'close-small',
  'dot',
  'down',
  'indeterminate',
  'left',
  'inline-right',
  'inline-right-bold',
  'inline-list-checkmark',
  'inline-list-ul',
  'minus',
  'plus',
  'right',
  'search',
  'up',
  'up-down',
  'watch-off',
  'watch-on',
  'inline-externallink',
  'menu',
  'right-bold-small',
  'down-small',
  'left-small',
  'up-small',
  'right-small',
  'nosafe-star-fill',
  'nosafe-star-half',
  'nosafe-star',
  'nosafe-lr-externallink',
  'nosafe-lr-right-small',
  'arrow-back',
  'arrow-up-down',
  'arrow-left-right',
  'externallink',
  'nosafe-lr-right-bold-small',
  'nosafe-lr-forward-small-bold',
  'nosafe-lr-forward-small',
  'inline-forward-small-bold',
  'inline-forward-small',
  'forward-small-bold',
  'forward-small',
  'backward',
  'forward',
];

export default iconNames;
