export const dataMock = [
  'Bosch und Microsoft entwickeln Softwareplattform für die nahtlose Vernetzung von Autos und Cloud',
  'Robert Bosch Venture Capital investiert in die Serie-B-Finanzierungsrunde von Recogni',
  'Eine neue Leistungsdimension: Biturbo-Kapp- und Gehrungssäge von Bosch für Profis',
  'Leistungsstärkster Akku-Bohrhammer mit SDS plus: Neuer Biturbo-Hammer von Bosch für Profis',
  'Breites Innenraumfilter-Programm von Bosch für Elektrofahrzeuge',
  'Bosch erhält Auszeichnung für integrierte Kommunikation',
  'Dank Bosch warnen ŠKODA-Fahrzeuge jetzt serienmäßig vor Falschfahrern',
  'Aufzug-Monitoring von Bosch Service Solutions verkürzt Ausfallzeiten und senkt Betriebskosten',
  'Avenar all-in-one 4000 Signalgeber setzt neue Maßstäbe im Brandschutz',
  'Bosch hält in der Corona-Krise Kurs und erzielt positives Ergebnis',
  'Grüne Laserdiode für optimale Sichtbarkeit: Neue Punktlaser-Generation von Bosch für Profis',
  'NEVONEX gewinnt fünf weitere starke Partner',
  'Zahnriemen in Öl jetzt neu im Werkstatt-Lieferprogramm für Antriebstechnik von Bosch',
  'Durchbruch in eine neue Leistungsdimension: Biturbo-Hämmer von Bosch für Profis',
  'Akkurat messen, einfach ablesen, kabellos übertragen: Robuste Laser-Entfernungsmesser von Bosch für Profis',
  'Kilometerstände aus verschiedenen Steuergeräten im Fahrzeug auslesen mit dem KTS 250 von Bosch',
  'CES 2021: Bosch setzt auf KI und Vernetzung – zum Schutz von Mensch und Natur',
  'Bosch Hämoglobin Monitor: Anämien ohne Blutuntersuchung frühzeitig erkennen',
  'Smarter Alltag, smarte Möglichkeiten',
  'Bosch Corona-Schnelltest liefert Ergebnis bei positiven Proben in weniger als 30 Minuten',
  '„Ich kann jedem nur empfehlen, den Kontakt mit dem Coronavirus möglichst zu vermeiden.“',
  'Bosch präsentiert Human Skin Temperature Detection Solution',
  'Connected Biking Lösung überzeugt in Las Vegas',
  'Robert Bosch Venture Capital investiert in Arris Composites',
  'Sensoren werden noch schlauer: KI personalisiert das Fitnesstracking',
  'Übersichtliche Aufbewahrung von Werkzeug und Zubehör: Bosch erweitert SystemBox-Sortiment um Größe M',
  'Akku-Druckluftpumpe für Mobilität, Freizeit und Sport: Bosch EasyPump – kompakt und vielseitig',
  'Aviotec: Videobasierte Branderkennung bei Dunkelheit dank neuer KI-Algorithmen',
  'Zukunftsmarkt Fahrzeugcomputer: Bosch erhält Aufträge in Milliardenhöhe',
  'Robert Bosch Venture Capital beteiligt sich an 6-Millionen-USD-Investitionsrunde in Sunlight',
  'Stationäre Brennstoffzelle: Bosch will 2024 mit Serienfertigung starten',
  'Bosch Service Solutions investiert in US-Start-up Sfara',
  'Bosch nimmt erstes 5G-Campusnetz in Betrieb',
  'Robert Bosch Venture Capital investiert in Aclimas 40 Millionen US Dollar Serie-B-Finanzierungsrunde',
  'Individueller Look für den Kultschrauber: Bosch Ixo jetzt nach Wunsch stylen',
  'Klassisches Design und 30 Prozent kürzere Ladezeit: Kultschrauber Ixo Classic ist zurück',
  'Robert Bosch Venture Capital beteiligt sich an Serie-B-Finanzierungsrunde von FMC über 20 Millionen USD',
  'Bosch liefert Wasserstoff-Heizkessel',
  'Bosch zündet den Turbo für die Elektromobilität',
  'Bosch und BASF gründen Joint Venture für digitale Technologien in der Landwirtschaft',
  'Bosch KI-Zukunftskompass: 60 Prozent der Deutschen wünschen sich einen stärkeren Einsatz von künstlicher Intelligenz im industriellen Umfeld',
  'Der Energiewende einen Schritt näher',
  'Bosch: Weltweit erster voll integrierter Splitscreen für Motorräder kommt auf die Straße',
  'Neuerungen der Kalibriervorrichtung DAS 3000 von Bosch für Fahrerassistenzsysteme',
  'Neue Flaggschiffe für die Holzbearbeitung: Biturbo-Sägen von Bosch für Profis',
  'Initialzündung für den Insassenschutz: Vor 40 Jahren brachte Bosch das elektronische Airbag-Steuergerät ins Auto',
  'Trennen leicht gemacht: EasyCut&Grind von Bosch für Heimwerker',
  'Das Bosch Smart Home Partnerprogramm nimmt mit der Mercedes-Benz S-Klasse weiter Fahrt auf',
  'Die Herbst-Highlights 2020 von Bosch Smart Home',
  'Bosch-Umfrage in Europa zur Zukunft des Antriebs: Befragte bevorzugen Vielfalt bei Antriebsarten',
  'Bosch eXchange Programm zur zeitwertgerechten Instandsetzung: Angebot an hydraulischen Lenksystemen deutlich erweitert',
  'Robert Bosch Venture Capital Co-Lead-Investor in Finanzierungsrunde über 10 Mio. USD für SiteAware',
  'Stadt, Land, Autobahn: Bosch bereitet dem klimaneutralen Transport den Weg',
  'Vollautomatisiertes und fahrerloses Parken kommt an den Flughafen Stuttgart',
  'Neuer Corona-Schnelltest von Bosch liefert zuverlässiges Ergebnis in 39 Minuten',
  'Bosch Motorsport ist exklusiver Lieferant von Hybridantrieben für die neue LMDh Serie',
  'Virtueller Beifahrer für mehr Sicherheit im Lkw-Verkehr',
  'Bosch und Weichai Power steigern Wirkungsgrad von Weichai Lkw-Dieselmotor auf 50 Prozent',
  'Kesseltechnik von Bosch reduziert CO2-Emissionen um 15 Prozent',
  'Strategische Kooperation: Bosch und SAP wollen mit neuem Standard Unternehmensprozesse vereinfachen',
  'Bosch eBike Systems bringt Fachhändler europaweit auf den neuesten Stand',
  'PowerStations für eBiker auf dem Alb-Crossing',
  'Bosch eBike Systems: Enge Zusammenarbeit mit komoot',
  'IFA 2020: Vernetzt in den Alltag von morgen',
  'Neu: Zündkerze EVO von Bosch mit hoher Widerstandsfestigkeit',
  'Bosch: Die Mobilität der Zukunft braucht die Brennstoffzelle',
  'Ford, Bedrock und Bosch testen fahrerloses Parken in Nordamerika',
  'Bosch präsentiert mit Avenar die nächste Generation Brandmelderzentralen',
  'Sicherheit to go mit Spexor von Bosch',
  'Jan Brockmann wird neuer Vorsitzender der Geschäftsführung der Bosch Thermotechnik GmbH',
  'Nora Klug wird Chefjuristin der Robert Bosch GmbH',
  'Vivatmo App erhält PneumoDigital-Siegel',
  'Klimaneutralität: Bosch baut Versorgung mit regenerativen Energien aus',
  'Bosch Smart Home ist ab sofort Apple HomeKit kompatibel',
  'Aerotwin-Scheibenwischer von Bosch mit weiterentwickeltem Wischgummiprofil',
  'Bosch reagiert mit seinem breiten Batterieprogramm auf aktuelle Marktanforderungen',
  'Komplexe Werkstattprobleme schneller lösen mit der Visual Connect App von Bosch',
  'Esitronic 2.0 von Bosch: Zukunftssicheres und effizientes Arbeiten dank neuster Updates',
  'Bosch und BASF gründen Projekthaus für smarte Aussaat- und Düngelösungen',
  'Abgastemperatursensor und Stickoxidsensor ergänzen das Werkstattprogramm von Bosch',
  'Neues E-Learning Angebot von Bosch vermittelt Werkstatt Know-how ortsunabhängig, live und kostengünstig',
  'Wussten Sie schon, dass…?',
  'Bosch bündelt Software- und Elektronikkompetenz in einem 17 000 Mitarbeiter starken Geschäftsbereich',
  'NEVONEX verdoppelt die Anzahl seiner Partner',
  'Wie Autos und Infrastruktur beim automatisierten Fahren in der Stadt zusammenarbeiten',
  'Bosch bringt neue Air Flux Serie auf den Markt',
  'Bosch und Gardena gründen Akku-Allianz',
  'Effizienzschub für gewerbliche Verwender: Bosch öffnet Professional 18V System für Profi-Marken',
  'Bosch treibt Innovationen voran und öffnet Akku-Plattform',
  'Grüne Laserdioden für optimale Sichtbarkeit: Neue Kombi- und Linienlaser von Bosch für Profis',
  'Größte Vielfalt an Reinigungszubehör auf dem Markt: Hochgeschwindigkeits-Reiniger Dremel Versa',
  'Einzigartiger Linienlaser mit integriertem Maßband: Der Atino von Bosch für Heimwerker',
  'Hannover Messe: Bosch-Lösungen für die Industrie',
  'Wie Bosch-Fabriken den Klimaschutz vorantreiben',
  'CO₂-Beratung: Bosch unterstützt produzierende Unternehmen auf dem Weg zur Klimaneutralität',
  'Fü ein noch breiteres Anwendungsspektrum: Neue X-Lock-Zubehöre von Bosch für Profis',
  'Bosch eröffnet wasserstofffähige Brennstoffzellen-Pilotanlage am Standort Wernau',
  '3D-Druck setzt neue Maßstäbe für die industrielle Massenproduktion',
  'Personelle Veränderungen in der Geschäftsführung der Robert Bosch GmbH',
  'Die Zukunft ist heute',
  'Vielfältig, kreativ, exklusiv',
  'Mehr Power für Drive Units',
  'Digitaler Begleiter für mehr Sicherheit beim eBiken',
  'Intelligent vernetzter Tourenbegleiter',
  'Für maximalen Fahrspaß beim eMountainbike',
  'Einen Touch smarter, innovativer und vernetzter',
  'Werkstattsoftware Esitronic erlaubt umfassende Arbeiten an zugriffgeschützten Mercedes-Benz Fahrzeugen',
  'Für vielseitige, schnelle Schnitte in Holz und Laminat: Neue Bosch-Stichsägeblätter mit Hartmetall-Technologie',
  'Telemetriesystem RaceConnect von Bosch Motorsport',
  'Tag der Verkehrssicherheit: Wie der Bosch eCall Leben rettet',
  'Schnell, sauber und komfortabel: Zwei neue Kettensägen von Bosch',
  'Bosch Healthcare Solutions setzt auf Nachhaltigkeit',
];
